/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avaliacao; // a interface que estamos enviando é a interface do mercado, pois apesar de nós mandarmos os outros tendo suas caracteríticas também, o mercado é o mais importante, além de que os outros são apenas para caracterizar eles e o próprio mercado em si

/**
 *
 * @author Aluno
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_funcionario = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        c_funcionario = new javax.swing.JTextField();
        c_fornecedor = new javax.swing.JTextField();
        t_fornecedor = new javax.swing.JLabel();
        btn_enviar2 = new javax.swing.JButton();
        t_mercado = new javax.swing.JLabel();
        t_produto = new javax.swing.JLabel();
        c_produto = new javax.swing.JTextField();
        btn_enviar3 = new javax.swing.JButton();
        t_cliente = new javax.swing.JLabel();
        c_cliente = new javax.swing.JTextField();
        btn_enviar4 = new javax.swing.JButton();
        t_nome = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        btn_enviar5 = new javax.swing.JButton();
        t_cnpj = new javax.swing.JLabel();
        c_cnpj = new javax.swing.JTextField();
        btn_enviar6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t_funcionario.setText("Funcionário :");

        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        t_fornecedor.setText("Fornecedor :");

        btn_enviar2.setText("Enviar");
        btn_enviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar2ActionPerformed(evt);
            }
        });

        t_mercado.setText("MERCADO ESPECÍFICO");

        t_produto.setText("Produto :");

        btn_enviar3.setText("Enviar");
        btn_enviar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar3ActionPerformed(evt);
            }
        });

        t_cliente.setText("Cliente :");

        btn_enviar4.setText("Enviar");
        btn_enviar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar4ActionPerformed(evt);
            }
        });

        t_nome.setText("Nome :");

        btn_enviar5.setText("Enviar");
        btn_enviar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar5ActionPerformed(evt);
            }
        });

        t_cnpj.setText("Cnpj :");

        btn_enviar6.setText("Enviar");
        btn_enviar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(t_mercado))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_enviar6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(t_cnpj)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_enviar3)
                                        .addComponent(c_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_enviar4)
                                        .addComponent(btn_enviar2)
                                        .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_enviar5)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_enviar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t_funcionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_fornecedor)
                                .addGap(18, 18, 18)
                                .addComponent(c_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(t_cliente)
                                .addComponent(t_produto))
                            .addComponent(t_nome))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_mercado)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_funcionario)
                    .addComponent(c_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enviar)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_fornecedor)
                    .addComponent(c_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_enviar2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_produto)
                    .addComponent(c_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_enviar3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cliente)
                    .addComponent(c_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enviar4)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nome)
                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_enviar5)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cnpj)
                    .addComponent(c_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_enviar6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
       System.out.println(c_funcionario.getText()); // aqui ele vai chamar o funcionario
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_enviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar2ActionPerformed
       System.out.println(c_fornecedor.getText()); // aqui ele vai chamar o fornecedor
    }//GEN-LAST:event_btn_enviar2ActionPerformed

    private void btn_enviar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar3ActionPerformed
       System.out.println(c_produto.getText()); // aqui ele vai chamar o produto
    }//GEN-LAST:event_btn_enviar3ActionPerformed

    private void btn_enviar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar4ActionPerformed
       System.out.println(c_cliente.getText()); //aqui ele vai chamar o cliente
    }//GEN-LAST:event_btn_enviar4ActionPerformed

    private void btn_enviar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar5ActionPerformed
        System.out.println(c_nome.getText()); //aqui ele vai chamar o nome
    }//GEN-LAST:event_btn_enviar5ActionPerformed

    private void btn_enviar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar6ActionPerformed
       System.out.println(c_cnpj.getText()); //aqui ele vai chamar o cnpj do mercado
    }//GEN-LAST:event_btn_enviar6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_enviar2;
    private javax.swing.JButton btn_enviar3;
    private javax.swing.JButton btn_enviar4;
    private javax.swing.JButton btn_enviar5;
    private javax.swing.JButton btn_enviar6;
    private javax.swing.JTextField c_cliente;
    private javax.swing.JTextField c_cnpj;
    private javax.swing.JTextField c_fornecedor;
    private javax.swing.JTextField c_funcionario;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_produto;
    private javax.swing.JLabel t_cliente;
    private javax.swing.JLabel t_cnpj;
    private javax.swing.JLabel t_fornecedor;
    private javax.swing.JLabel t_funcionario;
    private javax.swing.JLabel t_mercado;
    private javax.swing.JLabel t_nome;
    private javax.swing.JLabel t_produto;
    // End of variables declaration//GEN-END:variables
}
   
